****
## JSON exercise

Using data in file 'data/world_bank_projects.json' and the techniques demonstrated above,
1. Find the 10 countries with most projects
2. Find the top 10 major project themes (using column 'mjtheme_namecode')
3. In 2. above you will notice that some entries have only the code and the name is missing. Create a dataframe with the missing names filled in.

In [1]:
import pandas as pd
import numpy as np
import json
from pandas.io.json import json_normalize

In [33]:
data = json.load((open('data/world_bank_projects.json')))
#df = pd.read_json('data/word_bank_projects.json')
#df.shape

In [21]:
df= pd.read_json('data/world_bank_projects.json')

In [22]:
df.shape

(500, 50)

In [44]:
pd.set_option('display.max_columns', None)
df.head()

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,docty,envassesmentcategorycode,grantamt,ibrdcommamt,id,idacommamt,impagency,lendinginstr,lendinginstrtype,lendprojectcost,majorsector_percent,mjsector_namecode,mjtheme,mjtheme_namecode,mjthemecode,prodline,prodlinetext,productlinetype,project_abstract,project_name,projectdocs,projectfinancialtype,projectstatusdisplay,regionname,sector,sector1,sector2,sector3,sector4,sector_namecode,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,{'$oid': '52b213b38594d8a2be17c780'},1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,"Project Information Document,Indigenous People...",C,0,0,P129828,130000000,MINISTRY OF EDUCATION,Investment Project Financing,IN,550000000,"[{'Percent': 46, 'Name': 'Education'}, {'Perce...","[{'code': 'EX', 'name': 'Education'}, {'code':...",[Human development],"[{'code': '8', 'name': 'Human development'}, {...","8,11",PE,IBRD/IDA,L,{'cdata': 'The development objective of the Se...,Ethiopia General Education Quality Improvement...,"[{'DocDate': '28-AUG-2013', 'EntityID': '09022...",IDA,Active,Africa,"[{'Name': 'Primary education'}, {'Name': 'Seco...","{'Percent': 46, 'Name': 'Primary education'}","{'Percent': 26, 'Name': 'Secondary education'}","{'Percent': 16, 'Name': 'Public administration...","{'Percent': 12, 'Name': 'Tertiary education'}","[{'code': 'EP', 'name': 'Primary education'}, ...","ET,BS,ES,EP",IBRD,Active,N,"{'Percent': 100, 'Name': 'Education for all'}","[{'code': '65', 'name': 'Education for all'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethi...
1,{'$oid': '52b213b38594d8a2be17c781'},2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,"Project Information Document,Integrated Safegu...",C,4700000,0,P144674,0,MINISTRY OF FINANCE,Specific Investment Loan,IN,5700000,"[{'Percent': 70, 'Name': 'Public Administratio...","[{'code': 'BX', 'name': 'Public Administration...","[Economic management, Social protection and ri...","[{'code': '1', 'name': 'Economic management'},...","1,6",RE,Recipient Executed Activities,L,NaN,TN: DTF Social Protection Reforms Support,"[{'DocDate': '29-MAR-2013', 'EntityID': '00033...",OTHER,Active,Middle East and North Africa,[{'Name': 'Public administration- Other social...,"{'Percent': 70, 'Name': 'Public administration...","{'Percent': 30, 'Name': 'General public admini...",NaN,NaN,"[{'code': 'BS', 'name': 'Public administration...","BZ,BS",IBRD,Active,N,"{'Percent': 30, 'Name': 'Other economic manage...","[{'code': '24', 'name': 'Other economic manage...","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en
2,{'$oid': '52b213b38594d8a2be17c782'},2014,November,2013-11-01T00:00:00Z,MINISTRY OF FINANCE AND ECONOMIC DEVEL,NaN,Tuvalu!$!TV,TV,Tuvalu,Tuvalu,"Resettlement Plan,Environmental Assessment,Int...",B,0,0,P145310,6060000,MINISTRY OF TRANSPORT AND COMMUNICATIONS,Investment Project Financing,IN,6060000,"[{'Percent': 100, 'Name': 'Transportation'}]","[{'code': 'TX', 'name': 'Transportation'}]","[Trade and integration, Public sector governan...","[{'code': '5', 'name': 'Trade and integration'...","5,2,11,6",PE,IBRD/IDA,L,NaN,Tuvalu Aviation Investment Project - Additiona...,"[{'DocDate': '21-OCT-2013', 'EntityID': '00033...",IDA,Active,East Asia and Pacific,[{'Name': 'Rural and Inter-Urban Roads and Hig...,"{'Percent': 100, 'Name': 'Rural and Inter-Urba...",NaN,NaN,NaN,"[{'code': 'TI', 'name': 'Rural and Inter-Urban...",TI,IBRD,Active,Y,"{'Percent': 46, 'Name': 'Regional integration'}","[{'code': '47', 'name': 'Regional integration'...","52,81,25,47",6060000,6060000,http://www.worldbank.org/projects/P145310?lang=en
3,{'$oid': '52b213b38594d8a2be17c783'},2014,October,2013-10-31T00:00:00Z,MIN. OF PLANNING AND INT'L COOPERATION,NaN,Republic of Yemen!$!RY,RY,Republic of Yemen,"Yemen, Republic of","Procurement Plan,Project Information Document,...",C,1500000,0,P144665,0,LABOR INTENSIVE PUBLIC WORKS PROJECT PMU,Technical Assistance Loan,IN,1500000,"[{'Percent': 100, 'Name': 'Health and other so...","[{'code': 'JX', 'name': 'Health and other soci...","[Social dev/gender/inclusion, Social dev/gende...","[{'code': '7', 'name': 'Social dev/gender/incl...","7,7",RE,Recipient Executed Activities,L,NaN,Gov't and Civil Society Organization Partnership,"[{'DocDate': '15-MAY-2013', 'EntityID': '00035...",OTHER,Active,Middle East and North Africa,[{'Name': 'Other social services'}],"{'Percent': 100, 'Name': 'Other social services'}",NaN,NaN,NaN,"[{'code': 'JB', 'name': 'Other social services'}]",JB,IBRD,Active,N,"{'Percent': 50, 'Name': 'Participation and civ...","[{'code': '57', 'name': 'Participation and civ...","59,57",0,1500000,http://www.worldbank.org/projects/P144665?lang=en
4,{'$oid': '52b213b38594d8a2be17c784'},2014,October,2013-10-31T00:00:00Z,MINISTRY OF FINANCE,2019-04-30T00:00:00Z,Kingdom of Lesotho!$!LS,LS,Kingdom of Lesotho,Lesotho,"Project Information Document,Integrated Safegu...",B,0,0,P144933,13100000,MINISTRY OF TRADE AND INDUSTRY,Investment Project Financing,IN,15000000,"[{'Percent': 50, 'Name': 'Industry and trade'}...","[{'code': 'YX', 'name': 'Industry and trade'},...","[Trade and integration, Financial and private ...","[{'code': '5', 'name': 'Trade and integration'...","5,4",PE,IBRD/IDA,L,{'cdata': 'The development objective of the Se...,Second Private Sector Competitiveness and Econ...,"[{'DocDate': '06-SEP-2013', 'EntityID': '09022...",IDA,Active,Africa,[{'Name': 'General industry and trade sector'}...,"{'Percent': 50, 'Name': 'General industry and ...","{'Percent': 40, 'Name': 'Other industry'}","{'Percent': 10, 'Name': 'SME Finance'}",NaN,"[{'code': 'YZ', 'name': 'General industry and ...","FH,YW,YZ",IBRD,Active,N,"{'Percent': 30, 'Name': 'Export development an...","[{'code': '45', 'name': 'Export development an...","41,45",13100000,13100000,http://www.worldbank.org/projects/P144933/seco...

In [41]:
df.columns

Index(['_id', 'approvalfy', 'board_approval_month', 'boardapprovaldate',
       'borrower', 'closingdate', 'country_namecode', 'countrycode',
       'countryname', 'countryshortname', 'docty', 'envassesmentcategorycode',
       'grantamt', 'ibrdcommamt', 'id', 'idacommamt', 'impagency',
       'lendinginstr', 'lendinginstrtype', 'lendprojectcost',
       'majorsector_percent', 'mjsector_namecode', 'mjtheme',
       'mjtheme_namecode', 'mjthemecode', 'prodline', 'prodlinetext',
       'productlinetype', 'project_abstract', 'project_name', 'projectdocs',
       'projectfinancialtype', 'projectstatusdisplay', 'regionname', 'sector',
       'sector1', 'sector2', 'sector3', 'sector4', 'sector_namecode',
       'sectorcode', 'source', 'status', 'supplementprojectflg', 'theme1',
       'theme_namecode', 'themecode', 'totalamt', 'totalcommamt', 'url'],
      dtype='object')

In [43]:
df[df.columns[11:20]]

,envassesmentcategorycode,grantamt,ibrdcommamt,id,idacommamt,impagency,lendinginstr,lendinginstrtype,lendprojectcost
0,C,0,0,P129828,130000000,MINISTRY OF EDUCATION,Investment Project Financing,IN,550000000
1,C,4700000,0,P144674,0,MINISTRY OF FINANCE,Specific Investment Loan,IN,5700000
2,B,0,0,P145310,6060000,MINISTRY OF TRANSPORT AND COMMUNICATIONS,Investment Project Financing,IN,6060000
3,C,1500000,0,P144665,0,LABOR INTENSIVE PUBLIC WORKS PROJECT PMU,Technical Assistance Loan,IN,1500000
4,B,0,0,P144933,13100000,MINISTRY OF TRADE AND INDUSTRY,Investment Project Financing,IN,15000000
5,C,0,0,P146161,10000000,NaN,Investment Project Financing,IN,66400000
6,A,0,500000000,P121185,0,MINISTRY OF ROAD TRANSPORT AND HIGHWAYS,Specific Investment Loan,IN,1146050000
7,C,27280000,0,P127033,0,NATIONAL ENERGY ADMINISTRATION,Investment Project Financing,IN,27280000
8,B,0,0,P130164,160000000,"PUBLIC WORKS DEPARTMANT, RAJASTHAN",Specific Investment Loan,IN,227000000
9,NaN,0,200000000,P130903,0,MINISTRY OF FINANCE,Development Policy Lending,AD,200000000
10,B,7530000,0,P145339,0,"MINISTRY OF AGRICULTURE, COOPERATIVES AND RURA...",Specific Investment Loan,IN,7530000
11,B,0,0,P146653,250000000,NaN,Investment Project Financing,IN,250000000
12,C,0,0,P144140,97000000,MINISTRY OF COMMUNICATIONS,Specific Investment Loan,IN,97000000
13,B,0,15000000,P130975,25000000,MINISTRY OF INFRASTRUCTURE,Specific Investment Loan,IN,92000000
14,C,9500000,0,P144832,0,MINISTRY OF PLANNING AND INTERNATIONAL COOPERA...,Technical Assistance Loan,IN,10000000
15,B,0,0,P145545,20000000,LAND TRANSPORT AUTHORITY,Investment Project Financing,IN,20000000
16,B,0,0,P145938,5000000,MINISTRY OF AGRICULTURE AND FISHERIES,Investment Project Financing,IN,5000000
17,B,85400000,0,P132616,0,MINISTRY OF EDUCATION,Emergency Recovery Loan,IN,85400000
18,B,13450000,0,P146271,0,MINISTRY OF HEALTH,Investment Project Financing,IN,13450000
19,C,4350000,0,P143979,0,MINISTRY OF FINANCE,Specific Investment Loan,IN,4550000
20,C,2000000,0,P132577,0,AGA KHAN DEVELOPMENT NETWORK (AKDN),Specific Investment Loan,IN,2000000
21,B,2750000,0,P145359,0,LALITPUR SUB-METROPOLITAN CITY,Specific Investment Loan,IN,2750000
22,B,50000000,0,P147689,0,MINISTRY OF MUNICIPAL AFFAIRS,Investment Project Financing,IN,53000000
23,C,2800000,0,P146109,0,MINISTRY OF HEALTH,Investment Project Financing,IN,2800000
24,F,0,34500000,P122812,0,MINISTRY OF AGRICULTURE,Investment Project Financing,IN,53250000
25,B,4500000,0,P123933,0,UNIVERSITY OF QUEENSLAND,Investment Project Financing,IN,6500000
26,NaN,0,0,P143025,20000000,MINISTRY OF FINANCE,Development Policy Lending,AD,20000000
27,C,0,0,P145057,2150000,PACIFIC AVIATION SECURITY OFFICE,Investment Project Financing,IN,2150000
28,B,0,0,P146021,3000000,MINISTRY OF DEVELOPMENT PLANNING AND COOPERATION,Investment Project Financing,IN,5500000
29,A,0,0,P146098,32000000,MINISTRY OF PUBLIC WORKS AND HOUSING,Investment Project Financing,IN,32000000
...,...,...,...,...,...,...,...,...,...
470,B,0,0,P129654,50000000,MINISTRY OF PUBLIC WORKS,Specific Investment Loan,IN,50000000
471,B,0,0,P131263,155000000,"IDCOL, POWER CELL, REB",Specific Investment Loan,IN,386000000
472,C,150000,0,P131631,0,GEF SECRETARIAT,Specific Investment Loan,IN,190000
473,C,150000,0,P132679,0,GEF SECRETARIAT,Specific Investment Loan,IN,180000
474,B,0,0,P112901,150000000,GOVERNMENT OF PUNJAB,Specific Investment Loan,IN,154000000
475,A,0,29600000,P118916,0,MINISTRY OF FINANCE,Specific Investment Loan,IN,79600000
476,B,0,0,P125996,448900000,VIETNAM ELECTRICITY (EVN)/MINISTRY OF INDUSTRY...,Specific Investment Loan,IN,800000000
477,B,0,0,P126962,40000000,MINISTRY OF AGRICULTURE AND WATER RESOURCES,Specific Investment Loan,IN,30400000
478,B,0,0,P131266,70000000,PROVINCE OF PUNJAB,Specific Investment Loan,IN,70000000
479,U,2510000,0,P130412,0,UT'Z CHE,Technical Assistance Loan,IN,2510000
480,C,350000,0,P131881,0,"MINISTRY OF MINES, ENERGY AND WATER DEVELOPMENT",Technical Assistance Loan,IN,350000
481,C,0,0,P121731,106000000,GOVERNMENT OF INDIA,Adaptable Program Loan,IN,151500000
482,B,0,0,P122486,60000000,"GOVERNMENT OF KARNATAKA, WATERSHED DEVELOPMENT...",Specific Investment Loan,IN,85700000
483,NaN,0,100000000,P124041,0,GOVERNMENT OF HIMACHAL PRADESH,Development Policy Lending,AD,100000000
484,B,5570000,0,P132238,0,"ILO, MINLAND & CFSI & BANK",Specific Investment Loan,IN,5730000
485,C,2900000,0,P131204,0,"NATIONAL EMERGENCY MANAGEMENT AGENCY, MOH, MOFALI",Emergency Recovery Loan,IN,2900000
486,C,2400000,0,P132097,0,SAVE THE CHILDREN INTERNATIONAL AND THE BANK,Technical Assistance Loan,IN,2400000
487,B,11690000,0,P121116,0,NATIONAL COMMISSION FOR BIODIVERSITY KNOWLEDGE...,Specific Investment Loan,IN,30890000
488,NaN,0,300000000,P126465,0,SECRETARIA DE FAZENDA,Development Policy Lending,AD,300000000
489,B,350000,0,P128763,0,UN-HABITAT,Technical Assistance Loan,IN,350000
490,C,800000,0,P131860,0,GOVERNMENT OF NEPAL,Specific Investment Loan,IN,800000
491,B,3650000,0,P123322,0,JOINT SERVICES COUNCIL,Technical Assistance Loan,IN,3650000
492,B,10000000,0,P128096,0,"DEPARTMENT OF EDUCATION, GOVERNMENT OF BALOCHI...",Emergency Recovery Loan,IN,14460000
493,C,150000,0,P132138,0,GEF SECRETARIAT,Specific Investment Loan,IN,150000
494,B,1510000,0,P129177,0,DEPARTMENT OF EDUCATION,Technical Assistance Loan,IN,1510000
495,C,50000,0,P127299,0,THE COMPETITIVENESS COMPANY,Technical Assistance Loan,IN,50000
496,NaN,0,0,P125298,20000000,MINISTRY OF FINANCE,Development Policy Lending,AD,20000000
497,B,20000000,0,P128309,0,MINISTRY OF AGRICULTURE AND PRODUCER ORGANISAT...,Specific Investment Loan,IN,20000000
498,B,0,80000000,P117243,0,INDONESIAN AGENCY FOR AGRICULTURAL RESEARCH AN...,Specific Investment Loan,IN,106000000
499,B,0,0,P126321,300000000,MINISTRY OF ROADS,Specific Investment Loan,IN,300000000

## 1. Find the 10 countries with most projects

In [31]:
df['countryname'].value_counts().head(10)

Republic of Indonesia              19
People's Republic of China         19
Socialist Republic of Vietnam      17
Republic of India                  16
Republic of Yemen                  13
Kingdom of Morocco                 12
Nepal                              12
People's Republic of Bangladesh    12
Africa                             11
Republic of Mozambique             11
Name: countryname, dtype: int64

## 2. Find the top 10 major project themes (using column 'mjtheme_namecode')

In [50]:
df['mjtheme_namecode'][0:10]

0    [{'code': '8', 'name': 'Human development'}, {...
1    [{'code': '1', 'name': 'Economic management'},...
2    [{'code': '5', 'name': 'Trade and integration'...
3    [{'code': '7', 'name': 'Social dev/gender/incl...
4    [{'code': '5', 'name': 'Trade and integration'...
5    [{'code': '6', 'name': 'Social protection and ...
6    [{'code': '2', 'name': 'Public sector governan...
7    [{'code': '11', 'name': 'Environment and natur...
8    [{'code': '10', 'name': 'Rural development'}, ...
9    [{'code': '2', 'name': 'Public sector governan...
Name: mjtheme_namecode, dtype: object

In [36]:
normalized_data = json_normalize(data, 'mjtheme_namecode')
normalized_data.code.value_counts().head(10)

11    250
10    216
8     210
2     199
6     168
4     146
7     130
5      77
9      50
1      38
Name: code, dtype: int64

## In 2. above you will notice that some entries have only the code and the name is missing. Create a dataframe with the missing names filled in.

In [39]:
normalized_data[normalized_data.name == ''].head()

   code name
1    11
13    6
17    8
19    7
24    2